// Word Lists for Spelling Practice App
// Each word has: { word: string, sentence: string }

const WORD_LISTS = {
    basic: {
        name: "100 Basic Words",
        description: "Essential everyday words",
        words: [
            { word: "the", sentence: "The cat sat on the mat." },
            { word: "and", sentence: "Bread and butter go well together." },
            { word: "have", sentence: "I have a new book to read." },
            { word: "that", sentence: "I know that you are right." },
            { word: "for", sentence: "This gift is for you." },
            { word: "not", sentence: "I am not feeling well today." },
            { word: "with", sentence: "I went to the park with my friend." },
            { word: "you", sentence: "You are doing a great job." },
            { word: "this", sentence: "This is my favorite color." },
            { word: "but", sentence: "I wanted to go, but it rained." },
            { word: "from", sentence: "The letter came from my grandmother." },
            { word: "they", sentence: "They are coming to the party." },
            { word: "been", sentence: "I have been waiting for an hour." },
            { word: "have", sentence: "Do you have any questions?" },
            { word: "were", sentence: "They were happy to see us." },
            { word: "what", sentence: "What time is dinner?" },
            { word: "when", sentence: "When will you arrive?" },
            { word: "your", sentence: "Is this your umbrella?" },
            { word: "said", sentence: "She said hello to everyone." },
            { word: "there", sentence: "There is a bird in the tree." },
            { word: "each", sentence: "Each student received a prize." },
            { word: "which", sentence: "Which color do you prefer?" },
            { word: "their", sentence: "Their house is painted blue." },
            { word: "time", sentence: "What time does the movie start?" },
            { word: "will", sentence: "I will help you tomorrow." },
            { word: "about", sentence: "Tell me about your day." },
            { word: "many", sentence: "There are many stars in the sky." },
            { word: "then", sentence: "First eat dinner, then dessert." },
            { word: "them", sentence: "Give the books to them." },
            { word: "would", sentence: "Would you like some tea?" },
            { word: "write", sentence: "Please write your name here." },
            { word: "like", sentence: "I like chocolate ice cream." },
            { word: "these", sentence: "These flowers smell lovely." },
            { word: "come", sentence: "Please come to my party." },
            { word: "could", sentence: "Could you help me carry this?" },
            { word: "people", sentence: "Many people visited the museum." },
            { word: "than", sentence: "She is taller than her brother." },
            { word: "first", sentence: "This is my first day at school." },
            { word: "water", sentence: "Drink plenty of water every day." },
            { word: "other", sentence: "The other team won the game." },
            { word: "where", sentence: "Where did you put my keys?" },
            { word: "after", sentence: "We can play after lunch." },
            { word: "back", sentence: "Please put the book back on the shelf." },
            { word: "little", sentence: "The little kitten was very cute." },
            { word: "only", sentence: "There is only one cookie left." },
            { word: "round", sentence: "The ball is round." },
            { word: "great", sentence: "You did a great job on the test." },
            { word: "through", sentence: "The train went through the tunnel." },
            { word: "place", sentence: "This is a nice place to relax." },
            { word: "think", sentence: "I think we should leave now." }
        ]
    },

    common: {
        name: "500 Common Words",
        description: "Frequently used vocabulary",
        words: [
            { word: "because", sentence: "I stayed home because I was sick." },
            { word: "different", sentence: "Each snowflake is different." },
            { word: "important", sentence: "Exercise is important for health." },
            { word: "another", sentence: "Would you like another piece of cake?" },
            { word: "answer", sentence: "Please answer the question." },
            { word: "change", sentence: "Seasons change throughout the year." },
            { word: "thought", sentence: "I thought about it carefully." },
            { word: "between", sentence: "The park is between the school and library." },
            { word: "something", sentence: "There is something in my eye." },
            { word: "without", sentence: "I cannot live without music." },
            { word: "before", sentence: "Wash your hands before eating." },
            { word: "building", sentence: "That building is very tall." },
            { word: "children", sentence: "The children played in the garden." },
            { word: "country", sentence: "Which country would you like to visit?" },
            { word: "enough", sentence: "Do we have enough food for everyone?" },
            { word: "example", sentence: "Can you give me an example?" },
            { word: "family", sentence: "My family loves to travel." },
            { word: "friend", sentence: "She is my best friend." },
            { word: "government", sentence: "The government announced new policies." },
            { word: "group", sentence: "A group of students went on the trip." },
            { word: "however", sentence: "It was cold; however, we went outside." },
            { word: "information", sentence: "I need more information about this." },
            { word: "interest", sentence: "She has an interest in music." },
            { word: "together", sentence: "Let us work together on this project." },
            { word: "language", sentence: "Learning a new language is fun." },
            { word: "later", sentence: "I will call you later." },
            { word: "minute", sentence: "Wait just one minute please." },
            { word: "money", sentence: "She saved her money for a new bike." },
            { word: "morning", sentence: "Good morning, how are you?" },
            { word: "mother", sentence: "My mother bakes delicious cookies." },
            { word: "nothing", sentence: "There is nothing to worry about." },
            { word: "number", sentence: "What is your phone number?" },
            { word: "often", sentence: "I often walk to school." },
            { word: "perhaps", sentence: "Perhaps we could try again tomorrow." },
            { word: "picture", sentence: "This picture shows our whole family." },
            { word: "problem", sentence: "Can you help me solve this problem?" },
            { word: "question", sentence: "That is a good question." },
            { word: "really", sentence: "I really enjoyed the movie." },
            { word: "remember", sentence: "Do you remember where you put it?" },
            { word: "school", sentence: "School starts at eight o'clock." },
            { word: "several", sentence: "I have read several books this month." },
            { word: "should", sentence: "You should eat more vegetables." },
            { word: "started", sentence: "The game started at noon." },
            { word: "story", sentence: "Tell me a bedtime story." },
            { word: "system", sentence: "The solar system has eight planets." },
            { word: "today", sentence: "Today is a beautiful day." },
            { word: "toward", sentence: "Walk toward the light." },
            { word: "understand", sentence: "I understand the instructions now." },
            { word: "until", sentence: "Wait here until I return." },
            { word: "usually", sentence: "I usually wake up early." }
        ]
    },

    frequent: {
        name: "1000 Frequent Words",
        description: "Extended vocabulary list",
        words: [
            { word: "absolutely", sentence: "I absolutely love this song." },
            { word: "actually", sentence: "Actually, I changed my mind." },
            { word: "although", sentence: "Although it was raining, we went hiking." },
            { word: "appreciate", sentence: "I appreciate your help very much." },
            { word: "beautiful", sentence: "The sunset was beautiful tonight." },
            { word: "beginning", sentence: "This is just the beginning of our journey." },
            { word: "believe", sentence: "I believe you can do it." },
            { word: "business", sentence: "He started his own business." },
            { word: "calendar", sentence: "Mark the date on your calendar." },
            { word: "carefully", sentence: "Please read the instructions carefully." },
            { word: "certainly", sentence: "I will certainly be there." },
            { word: "comfortable", sentence: "This chair is very comfortable." },
            { word: "community", sentence: "Our community works together well." },
            { word: "completely", sentence: "I completely agree with you." },
            { word: "continue", sentence: "Please continue with your presentation." },
            { word: "decision", sentence: "Making a decision can be difficult." },
            { word: "definitely", sentence: "I will definitely come to the party." },
            { word: "describe", sentence: "Can you describe what you saw?" },
            { word: "develop", sentence: "We need to develop a new plan." },
            { word: "difference", sentence: "Can you tell the difference?" },
            { word: "difficult", sentence: "This puzzle is quite difficult." },
            { word: "direction", sentence: "Which direction should we go?" },
            { word: "discover", sentence: "Scientists discover new species every year." },
            { word: "education", sentence: "Education opens many doors." },
            { word: "especially", sentence: "I love all fruits, especially mangoes." },
            { word: "everything", sentence: "Everything will be alright." },
            { word: "experience", sentence: "This was an amazing experience." },
            { word: "favorite", sentence: "What is your favorite color?" },
            { word: "finally", sentence: "We finally reached our destination." },
            { word: "generally", sentence: "I generally prefer tea over coffee." },
            { word: "happiness", sentence: "Happiness comes from within." },
            { word: "immediate", sentence: "We need an immediate response." },
            { word: "including", sentence: "Everyone came, including the new students." },
            { word: "knowledge", sentence: "Knowledge is power." },
            { word: "necessary", sentence: "Water is necessary for life." },
            { word: "opportunity", sentence: "This is a great opportunity." },
            { word: "particular", sentence: "Is there a particular reason?" },
            { word: "position", sentence: "What position do you play?" },
            { word: "possible", sentence: "Anything is possible if you try." },
            { word: "probably", sentence: "It will probably rain tomorrow." },
            { word: "recognize", sentence: "I did not recognize her at first." },
            { word: "situation", sentence: "We need to assess the situation." },
            { word: "sometimes", sentence: "Sometimes I like to read quietly." },
            { word: "special", sentence: "Today is a special occasion." },
            { word: "suddenly", sentence: "Suddenly, the lights went out." },
            { word: "surprise", sentence: "The gift was a complete surprise." },
            { word: "therefore", sentence: "It was late; therefore, we left." },
            { word: "throughout", sentence: "Flowers bloomed throughout the garden." },
            { word: "tomorrow", sentence: "Tomorrow is another day." },
            { word: "whether", sentence: "I wonder whether it will snow." }
        ]
    },

    misspelt: {
        name: "Commonly Misspelt Words",
        description: "Words people often spell incorrectly",
        words: [
            { word: "accommodate", sentence: "The hotel can accommodate fifty guests." },
            { word: "occurrence", sentence: "This is a rare occurrence." },
            { word: "separate", sentence: "Please separate the colors from whites." },
            { word: "necessary", sentence: "Is it really necessary to go?" },
            { word: "definitely", sentence: "I will definitely be there." },
            { word: "receive", sentence: "Did you receive my message?" },
            { word: "believe", sentence: "I believe in you." },
            { word: "achieve", sentence: "You can achieve your goals." },
            { word: "weird", sentence: "That was a weird coincidence." },
            { word: "their", sentence: "Their car is parked outside." },
            { word: "conscience", sentence: "My conscience told me to apologize." },
            { word: "rhythm", sentence: "The song has a catchy rhythm." },
            { word: "embarrass", sentence: "I did not mean to embarrass you." },
            { word: "millennium", sentence: "We entered a new millennium in 2000." },
            { word: "restaurant", sentence: "Let us meet at the restaurant." },
            { word: "immediately", sentence: "Please respond immediately." },
            { word: "independent", sentence: "She is very independent." },
            { word: "occasion", sentence: "This is a special occasion." },
            { word: "recommend", sentence: "I recommend this book highly." },
            { word: "exaggerate", sentence: "Do not exaggerate the story." },
            { word: "pronunciation", sentence: "Check your pronunciation carefully." },
            { word: "jewelry", sentence: "She wore beautiful jewelry." },
            { word: "cemetery", sentence: "The old cemetery is on the hill." },
            { word: "calendar", sentence: "I marked it on my calendar." },
            { word: "argument", sentence: "They had a small argument." },
            { word: "beginning", sentence: "This is the beginning of a journey." },
            { word: "committee", sentence: "The committee made a decision." },
            { word: "maintenance", sentence: "The car needs regular maintenance." },
            { word: "privilege", sentence: "It is a privilege to meet you." },
            { word: "questionnaire", sentence: "Please fill out this questionnaire." },
            { word: "parallel", sentence: "The two lines are parallel." },
            { word: "guarantee", sentence: "I guarantee you will love it." },
            { word: "harass", sentence: "Do not harass the animals." },
            { word: "lieutenant", sentence: "The lieutenant gave the orders." },
            { word: "miniature", sentence: "She collects miniature figurines." },
            { word: "neighbor", sentence: "My neighbor has a friendly dog." },
            { word: "noticeable", sentence: "The change was very noticeable." },
            { word: "pastime", sentence: "Reading is my favorite pastime." },
            { word: "perseverance", sentence: "Success requires perseverance." },
            { word: "possession", sentence: "This is my most prized possession." },
            { word: "publicly", sentence: "The results were announced publicly." },
            { word: "referred", sentence: "She referred me to a specialist." },
            { word: "relevant", sentence: "Please share only relevant information." },
            { word: "schedule", sentence: "What is your schedule for today?" },
            { word: "sergeant", sentence: "The sergeant led the training." },
            { word: "threshold", sentence: "We crossed the threshold of success." },
            { word: "twelfth", sentence: "December is the twelfth month." },
            { word: "tyranny", sentence: "The people fought against tyranny." },
            { word: "unanimous", sentence: "The vote was unanimous." },
            { word: "vacuum", sentence: "Please vacuum the living room." }
        ]
    },

    academic: {
        name: "Academic Words",
        description: "Words common in academic writing",
        words: [
            { word: "analysis", sentence: "The analysis revealed interesting patterns." },
            { word: "approach", sentence: "We need a different approach to this problem." },
            { word: "area", sentence: "This area requires further research." },
            { word: "assessment", sentence: "The assessment will be next week." },
            { word: "assume", sentence: "Do not assume anything without evidence." },
            { word: "authority", sentence: "She spoke with great authority." },
            { word: "available", sentence: "The data is available online." },
            { word: "benefit", sentence: "Exercise has many health benefits." },
            { word: "concept", sentence: "This concept is difficult to understand." },
            { word: "consistent", sentence: "Be consistent in your efforts." },
            { word: "constitutional", sentence: "They discussed constitutional rights." },
            { word: "context", sentence: "Consider the historical context." },
            { word: "contract", sentence: "They signed a contract." },
            { word: "create", sentence: "Artists create beautiful works." },
            { word: "data", sentence: "The data supports our hypothesis." },
            { word: "definition", sentence: "What is the definition of this word?" },
            { word: "derived", sentence: "This word is derived from Latin." },
            { word: "distribution", sentence: "The distribution of resources was fair." },
            { word: "economic", sentence: "Economic factors affect everyone." },
            { word: "environment", sentence: "We must protect the environment." },
            { word: "established", sentence: "The company was established in 1990." },
            { word: "estimate", sentence: "Can you estimate the cost?" },
            { word: "evidence", sentence: "The evidence was conclusive." },
            { word: "export", sentence: "They export goods worldwide." },
            { word: "factors", sentence: "Several factors contributed to success." },
            { word: "financial", sentence: "Seek financial advice before investing." },
            { word: "formula", sentence: "Use this formula to calculate the area." },
            { word: "function", sentence: "Each part has a specific function." },
            { word: "identified", sentence: "The problem was quickly identified." },
            { word: "income", sentence: "Their income increased this year." },
            { word: "indicate", sentence: "The results indicate improvement." },
            { word: "individual", sentence: "Each individual has unique talents." },
            { word: "interpretation", sentence: "There are many interpretations of this text." },
            { word: "involved", sentence: "Many people were involved in the project." },
            { word: "issues", sentence: "We discussed important issues today." },
            { word: "labour", sentence: "The project required intensive labour." },
            { word: "legal", sentence: "Is this action legal?" },
            { word: "legislation", sentence: "New legislation was passed." },
            { word: "major", sentence: "This is a major breakthrough." },
            { word: "method", sentence: "Which method did you use?" },
            { word: "occur", sentence: "Accidents can occur unexpectedly." },
            { word: "percent", sentence: "Sales increased by ten percent." },
            { word: "period", sentence: "The Renaissance was a period of great art." },
            { word: "policy", sentence: "The company has a strict policy." },
            { word: "principle", sentence: "This is a basic principle of physics." },
            { word: "procedure", sentence: "Follow the procedure carefully." },
            { word: "process", sentence: "The process takes several steps." },
            { word: "required", sentence: "A passport is required for travel." },
            { word: "research", sentence: "The research was groundbreaking." },
            { word: "response", sentence: "We await your response." }
        ]
    },

    challenging: {
        name: "Challenging Words",
        description: "More difficult spelling challenges",
        words: [
            { word: "acquaintance", sentence: "He is an old acquaintance of mine." },
            { word: "acknowledgement", sentence: "She gave a brief acknowledgement." },
            { word: "acquiesce", sentence: "They had to acquiesce to the demands." },
            { word: "bureaucracy", sentence: "The bureaucracy slowed down the process." },
            { word: "camouflage", sentence: "The soldiers wore camouflage uniforms." },
            { word: "catastrophe", sentence: "The earthquake was a catastrophe." },
            { word: "conscientious", sentence: "She is a conscientious worker." },
            { word: "correspondence", sentence: "Please handle the correspondence." },
            { word: "counterfeit", sentence: "Beware of counterfeit money." },
            { word: "deceive", sentence: "Do not try to deceive me." },
            { word: "deteriorate", sentence: "The weather began to deteriorate." },
            { word: "dilemma", sentence: "I faced a difficult dilemma." },
            { word: "disappear", sentence: "The magician made the rabbit disappear." },
            { word: "discrepancy", sentence: "There was a discrepancy in the accounts." },
            { word: "entrepreneur", sentence: "The entrepreneur started a new business." },
            { word: "equilibrium", sentence: "The system reached equilibrium." },
            { word: "exhilarate", sentence: "The ride will exhilarate you." },
            { word: "fluorescent", sentence: "The room had fluorescent lights." },
            { word: "hemorrhage", sentence: "The patient had internal hemorrhage." },
            { word: "hierarchy", sentence: "The company has a clear hierarchy." },
            { word: "hygiene", sentence: "Good hygiene prevents illness." },
            { word: "idiosyncrasy", sentence: "Everyone has their own idiosyncrasy." },
            { word: "indigenous", sentence: "The indigenous plants are protected." },
            { word: "inoculate", sentence: "They inoculate children against disease." },
            { word: "irresistible", sentence: "The chocolate cake was irresistible." },
            { word: "liaison", sentence: "She works as a liaison between departments." },
            { word: "maneuver", sentence: "The pilot performed a tricky maneuver." },
            { word: "Mediterranean", sentence: "We sailed across the Mediterranean Sea." },
            { word: "mischievous", sentence: "The mischievous puppy chewed my shoes." },
            { word: "miscellaneous", sentence: "I have miscellaneous items to sort." },
            { word: "nauseous", sentence: "The motion made me feel nauseous." },
            { word: "occasionally", sentence: "I occasionally eat dessert for breakfast." },
            { word: "omniscient", sentence: "The narrator was omniscient." },
            { word: "onomatopoeia", sentence: "Buzz is an example of onomatopoeia." },
            { word: "paraphernalia", sentence: "The artist had all her paraphernalia." },
            { word: "pharmaceutical", sentence: "The pharmaceutical company developed new medicine." },
            { word: "phenomenon", sentence: "The northern lights are a beautiful phenomenon." },
            { word: "pneumonia", sentence: "He was hospitalized with pneumonia." },
            { word: "pseudonym", sentence: "The author wrote under a pseudonym." },
            { word: "psychology", sentence: "She studied psychology at university." },
            { word: "reconnaissance", sentence: "The soldiers went on reconnaissance." },
            { word: "reminiscence", sentence: "He shared a reminiscence of his youth." },
            { word: "rendezvous", sentence: "We agreed on a rendezvous point." },
            { word: "sacrilegious", sentence: "Some considered his art sacrilegious." },
            { word: "surveillance", sentence: "The building is under surveillance." },
            { word: "susceptible", sentence: "Children are susceptible to colds." },
            { word: "temperament", sentence: "She has a calm temperament." },
            { word: "thorough", sentence: "Please do a thorough check." },
            { word: "vengeance", sentence: "He sought vengeance for the wrong." },
            { word: "zucchini", sentence: "Add some zucchini to the stir fry." }
        ]
    }
};

// Helper function to get all words from enabled lists
function getWordsFromLists(enabledListIds) {
    const words = [];
    enabledListIds.forEach(listId => {
        if (WORD_LISTS[listId]) {
            words.push(...WORD_LISTS[listId].words);
        }
    });
    return words;
}

// Helper function to get list metadata
function getListMetadata() {
    return Object.entries(WORD_LISTS).map(([id, list]) => ({
        id,
        name: list.name,
        description: list.description,
        wordCount: list.words.length
    }));
}
